"""Git pre-commit hook installer and environment validator for Latch.

Installs a portable pre-commit hook script into .git/hooks/pre-commit
pointing directly to the active virtual environment Python interpreter.
"""

from __future__ import annotations
import os
from pathlib import Path
import shlex
import shutil
import stat
import sys
from typing import Optional


class HookInstallError(Exception):
    """Raised when git hook installation fails."""
    pass


def find_git_dir(start_path: str = ".") -> Path:
    """Recursively search upwards for the .git directory."""
    current = Path(start_path).resolve()
    for parent in [current, *current.parents]:
        git_dir = parent / ".git"
        if git_dir.exists():
            return git_dir
    raise HookInstallError(
        f"Not a git repository (or any of the parent directories): .git not found from '{start_path}'."
    )


def install_pre_commit_hook(
    repo_root: Optional[str] = None,
    python_path: Optional[str] = None,
) -> Path:
    """Install Latch as a pre-commit hook in .git/hooks/pre-commit.

    Args:
        repo_root: Root path of repository or None to auto-discover.
        python_path: Custom Python executable path or None to use sys.executable.

    Returns:
        Path to the installed pre-commit hook script.
    """
    search_root = repo_root or os.getcwd()
    git_dir = find_git_dir(search_root)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_file = hooks_dir / "pre-commit"
    backup_file = hooks_dir / "pre-commit.latch.bak"

    # Backup existing non-Latch hook if present and no backup already preserved
    if hook_file.exists() and not backup_file.exists():
        existing_content = hook_file.read_text(encoding="utf-8", errors="replace")
        if "Latch Pre-Commit Hook Guardrail" not in existing_content:
            shutil.copy2(hook_file, backup_file)

    py_exec = python_path or sys.executable
    quoted_py = shlex.quote(str(py_exec))

    script_content = (
        "#!/bin/sh\n"
        "# Latch Pre-Commit Hook Guardrail\n"
        "# Auto-generated by: python -m latch.cli install\n"
        "\n"
        f'exec {quoted_py} -m latch.cli check "$@"\n'
    )

    hook_file.write_text(script_content, encoding="utf-8")

    # Set executable permissions (chmod +x)
    try:
        current_mode = hook_file.stat().st_mode
        hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass

    return hook_file


def uninstall_pre_commit_hook(repo_root: Optional[str] = None) -> bool:
    """Uninstall Latch pre-commit hook and restore any previous hook backup.

    Args:
        repo_root: Root path of repository or None to auto-discover.

    Returns:
        True if hook was uninstalled or backup restored, False if no Latch hook found.
    """
    search_root = repo_root or os.getcwd()
    try:
        git_dir = find_git_dir(search_root)
    except HookInstallError:
        return False

    hooks_dir = git_dir / "hooks"
    hook_file = hooks_dir / "pre-commit"
    backup_file = hooks_dir / "pre-commit.latch.bak"

    if backup_file.exists():
        if hook_file.exists():
            hook_file.unlink()
        shutil.move(str(backup_file), str(hook_file))
        return True

    if hook_file.exists():
        content = hook_file.read_text(encoding="utf-8", errors="replace")
        if "Latch Pre-Commit Hook Guardrail" in content:
            hook_file.unlink()
            return True

    return False

